project:
  type: book

book:
  title: "Intro a la GenAI en AWS"
  author: "Juan Palmeros"
  chapters:
    - index.qmd
    - 01-Teoria-y-conceptos-basicos-de-redes-neuronales.qmd
    - 02-Teoria-y-conceptos-basicos-de-inteligencia-artificial-generativa.qmd

format:
  html:
    theme: cosmo

execute:
  freeze: auto
